/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockEditor: typeof import('./components/task/BlockEditor.vue')['default']
    DistributionPanel: typeof import('./components/task/DistributionPanel.vue')['default']
    DraftPreview: typeof import('./components/task/DraftPreview.vue')['default']
    MetricsPanel: typeof import('./components/task/MetricsPanel.vue')['default']
    PublishPanel: typeof import('./components/task/PublishPanel.vue')['default']
    PublishStatusCard: typeof import('./components/task/PublishStatusCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceList: typeof import('./components/task/SourceList.vue')['default']
    TaskForm: typeof import('./components/task/TaskForm.vue')['default']
    TaskProgress: typeof import('./components/task/TaskProgress.vue')['default']
    TitleSelector: typeof import('./components/task/TitleSelector.vue')['default']
  }
}
